<?php

/**
 * @file
 * Install, uninstall and updates.
 */

/**
 * @defgroup updates-7.x-to-1.x Updates from 7.x to 1.x
 * @{
 * Update functions from Drupal 7.x to Backdrop CMS 1.x.
 */

/**
 * Move Book Explorer settings from variables to config.
 */

function book_explorer_update_1000() {
  // Migrate variables to config.
  $config = config('book_explorer.settings');
  $config->set('block_mode', update_variable_get('book_explorer_block_mode', 'all pages'));

  $config->save();

  // Delete variables.
  update_variable_del('book_explorer_block_mode');
}

/*
 * @} End of "defgroup updates-7.x-to-1.x"
 * The next series of updates should start at 2000.
 */
